services:

  api:
    # image: voidtrek/mirrorino_backend:latest
    # image: mirrorino-api
    build: ./backend
    container_name: mirrorino_api
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - file_data:/data/files
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mirrorino_net

  frontend:
    # image: voidtrek/mirrorino_frontend:latest
    # image: mirrorino-frontend
    build: ./frontend
    container_name: mirrorino_frontend
    restart: unless-stopped
    environment:
      - NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE:-https://api.mirrorino.com}
      - NUXT_PUBLIC_SUPPORT_EMAIL=${NUXT_PUBLIC_SUPPORT_EMAIL:-}
      - NUXT_PUBLIC_SUPPORT_TELEGRAM_ID=${NUXT_PUBLIC_SUPPORT_TELEGRAM_ID:-}
      - NUXT_PUBLIC_SUPPORT_WEBSITE=${NUXT_PUBLIC_SUPPORT_WEBSITE:-}
    networks:
      - mirrorino_net

  db:
    image: postgres:16-alpine
    container_name: mirrorino_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: mirrorino
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: mirrorino
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mirrorino"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mirrorino_net

  redis:
    image: redis:7-alpine
    container_name: mirrorino_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redispass}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redispass}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - mirrorino_net

  nginx:
    # image: voidtrek/mirrorino_nginx:latest
    # image: mirrorino-nginx
    build: ./nginx
    container_name: mirrorino_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
      - frontend
    networks:
      - mirrorino_net

volumes:
  postgres_data:
  redis_data:
  file_data:

networks:
  mirrorino_net:
    driver: bridge
